### ISSUE TITLE
MyTube: Some videos play without sound

### ISSUE THREAD

**Issue by OnkelArmus** [lekma/repository.lekma#4] opened 2024-09-24 09:54 UTC
Some videos play without sound in the MyTube addon. On those videos the audio stream is shown as unknown. Here is an example: https://www.youtube.com/watch?v=UA8fMTIryWM

**Comment by lekma** [comment] 2024-09-26 12:13
works fine for me.
if you setup inputstream.adaptive as follow:
```
Stream selection type: Manual OSD
Manual stream selection mode: Audio / Video streams
```
you can then select a different audio stream while playing in the audio setting of the video.

maybe you can try that.
otherwise i have no idea (i know that the yt stable audio experiment has caused problems the last few weeks, but those seem to have been solved)

**Comment by lekma** [comment] 2024-09-26 12:15
also, please, try with latest release (3.2.1)

**Comment by OnkelArmus** [comment] 2024-09-26 14:12
With manual OSD it works for the old version and the new version also works without setting up inputstream for manual OSD. Links in favourites are broken in the new version but aren't needed anymore due to the new channels link in MyTube. Nice!
How can I do feature requests?

**Comment by lekma** [comment] 2024-09-26 14:41
> How can I do feature requests?

let's hear it here. I'll close this issue but I think you can still comment, if not just open another issue.

**Closed as completed by lekma** 2024-09-26 14:41 UTC

**Comment by OnkelArmus** [comment] 2024-09-26 14:47
On my first try it worked but now I'm affected again.
It looks like videos are more randomly affected. Also selecting a different audio stream did not work on first try. So I play the video, no sound, I switch through all audio streams and get a 50% success rate with fails and success throughout all AAC streams. Opus also present but I didn't try it by now. I stop the video and try again. This time only Opus works but with a success rate of 100%. Strange. For so far, all videos that did not play sound out of the box, play with Opus streams by default in the Kodi youtube addon.

My feature requests are support for SponsorBock and the option to disable fractional frame rates like in the youtube addon.
Background: For youtube videos with fractional frame rates and if Kodi is set to synchronize the screen refresh rate to the video, it causes a pause shortly after it was startet, which then may cause additional audio stuttering while kodi resynchronizes.

**Comment by lekma** [comment] 2024-09-26 15:42
> My feature requests are support for SponsorBock and the option to disable fractional frame rates like in the youtube addon.
Background: For youtube videos with fractional frame rates and if Kodi is set to synchronize the screen refresh rate to the video, it causes a pause shortly after it was startet, which then may cause additional audio stuttering while kodi resynchronizes.

sponsorblock probably yes (i already have some things in mind i want to experiment with regarding sb)
fractional framerates? what do you mean? (I can probably do that in service.yt-dlp the same way you can already limit framerate to 30fps, but I don't really know what you mean...)

**Comment by lekma** [comment] 2024-09-26 15:47
about your sound problem: I cannot really help (I tested on 2 different systems, and the video played fine first time)
I would suggest you look at the log (might have a hint there), maybe inputstream has some trouble, maybe reinstall, maybe exclude codecs in service.yt-dlp... i don't know, really

**Comment by OnkelArmus** [comment] 2024-09-26 16:09
I mean frame rates that don't end with ".00", like 23.97. It is called fractional frame rates in the youtube addon and can be disabled in settings > stream properties.

**Comment by lekma** [comment] 2024-09-26 16:18
oh, of course, sorry, i wasn't really paying attention :)
yeah i could probably do that in service.yt-dlp, i'll look into it

**Comment by OnkelArmus** [comment] 2024-09-26 16:27
Thanks!

**Comment by lekma** [comment] 2024-10-15 10:34
done, please try

**Comment by OnkelArmus** [comment] 2024-10-15 15:10
Thanks so far! Fractional frame rates are correctly ignored as set. SponsorBlock works and I've noticed that it's only partially supported. I don't know what that means, so describe what I've noticed. Kodi isn't very good at skipping so I had to reduce the amount of skip by 4500 ms in the SponsorBlock settings. This works fine in the youtube addon but has no effect in MyTube and invidious. I also tried to increase the amount of skip with no effect. In invidious (set to not proxy videos) there is a delay of about 5 - 10 seconds when skipping.
I preferred the SponsorBlock behaviour the way it was in the older invidious version and the youtube addon, where it skips by default and gives me the option to unskip. I don't always have the remote nearby and most of the time I want to skip.
I have a question: What does the optional dependency PySocks do? I found nothing of help when I looked it up.
I didn't give you my specs so here they are:
Raspberry Pi 4B 8GB (overclocked to 2100Mhz), LibreELEC 12.0.1
Are you interested in my log to diagnose videos without audio?

**Comment by lekma** [comment] 2024-10-15 15:35
> I have a question: What does the optional dependency PySocks do? I found nothing of help when I looked it up.

pysocks?? where??


> If the switching would happen before the video starts, like the Kodi youtube addon does, it would be perfect.

afaict the yt addon doesn't do anything, all of that is handled either by inputstream or kodi's own player (which one are you using when running the yt addon (or even an alternative one)?).


> I had to reduce the amount of skip by 4500 ms in the SponsorBlock settings.

what setting is that? is there a confusion between script.service.sponsorblock and service.sponsorblock?
the former is what interacts with yt addon the latter is the limited support one i wrote for mytube


> Raspberry Pi 4B 8GB (overclocked to 2100Mhz), LibreELEC 12.0.1

honestly that seems underpowered to be jumping around timelines and switching framerates willy, nilly :smile: 


> Are you interested in my log to diagnose videos without audio?

yeah i can't promise anything but i'm curious

also can you give me a video example with 23.967 fps from yt so i can observe what is happening

thanks

**Comment by lekma** [comment] 2024-10-15 15:39
s/23.967/23.976

**Comment by OnkelArmus** [comment] 2024-10-15 16:21
Sorry, I removed the part about fractional frame rates from my report a few minutes after I wrote it in hope to not cause confusion. Obviously I was to late. It works. I was interrupted while testing and did it with the wrong setting.
Actually the Pi has no problem running Kodi at all. It can even do 4k when set properly and I'm only at 1080. Even most codecs it has no hardware support for run flawless. It may still be affected by timing issues that don't occur on faster systems. It may also be possible that Kodi's unprecise skipping does not occur on faster systems. That's why I mention it. Slow skipping only occurs in the invidious addon and didn't occur before it was updated today. I didn't use it since I wrote the original issue here, so it may be something on youtube's side. As far as I understand the working of MyTube and invidious, the stream should be opened the same way in both addons, as long as proxying is disabled. If I'm correct with this statement, playback and skipping should behave the same in both addons.

> what setting is that? is there a confusion between script.service.sponsorblock and service.sponsorblock?

Yes, I was confused about it. Can you add the setting?

> pysocks?? where??

PySocks 1.6.8 is listed as an optional dependency in app info > dependencies.

**Comment by lekma** [comment] 2024-10-15 17:36
> Sorry, I removed the part about fractional frame rates from my report a few minutes after I wrote it in hope to not cause confusion. Obviously I was to late. It works. I was interrupted while testing and did it with the wrong setting.

no problem, i'm glad it works


> PySocks 1.6.8 is listed as an optional dependency in app info > dependencies.

that is an optional dependency of yt addon which is turn is an optional dependency  of MyTube and Invidious (https://github.com/anxdpanic/plugin.video.youtube/blob/master/addon.xml#L8) (I think you should be able to remove it safely, but I really don't know what it is used for in yt).


> As far as I understand the working of MyTube and invidious, the stream should be opened the same way in both addons, as long as proxying is disabled. If I'm correct with this statement, playback and skipping should behave the same in both addons.

mostly correct


I must admit i'm a bit confused, what you are saying is that in both Invidious and MyTube, when skipping it takes a long time to resume the video, correct? or is it only one and not the other (there might be clue here).

I used the same methods of skipping around the timeline that script.service.sponsorblock use, so I doubt it is linked to the service, but it could come from the fact that the playlists are quite different (you can test that by switching video stream while playing a video in invidious and in mytube, one should take way more time than the other).

your best bet to pinpoint what is happening, is to keep only service.sponsorblock, and one of the other two addons enabled, test and then disable the first one and enable the second, and test again and compare. a lot of these addons have services and http servers running in the background and that might put a strain on your system.

I really cannot reproduce what you're describing, I see a lag when resuming but at most it is one second
also have a look at kodi.log while this is happening, i sometimes see "ActiveAE - large audio sync error" when skipping around and that causes lag.

**Comment by OnkelArmus** [comment] 2024-10-16 07:42
> I must admit i'm a bit confused, what you are saying is that in both Invidious and MyTube, when skipping it takes a long time to resume the video, correct? or is it only one and not the other (there might be clue here).

It happens only in invidious. Manual skipping is affected the same way so the delay is not linked to service.sponsorblock.

I'm looking into the log and will provide it later.

**Comment by OnkelArmus** [comment] 2024-10-16 12:48
So, I made a small collection of log snippets for you. The full log is also available if necessary.
I could not fully reproduce the skip delay like it happened yesterday. There is still a delay and it's noticeable longer than in MyTube, but not as significant as yesterday. I did a few skips on the same video in both, MyTube and invidious for comparison.
There is another issue only present in MyTube so far, that causes the video stream to not play, but audio plays. When this happens, screen freezes with the busy wheel in the center. I can hit stop and I'm back in the menu with everything normal. This is most likely the same issue that causes audio to not play. It is more likely to affect audio over video. I would say every 20 videos I play video is affected. Audio is affected roughly every 5 - 10 videos. When I retry an affected video immediately, the problem persists, but can switch between audio or video not working. If I retry after a few minutes, the video plays fine, so something that causes the problem seems to stay cached before it times out. Logs for both cases are present.
I also encountered videos still playing with fractional frame rates. This happened only on older videos so far. Affected videos are the almost 30 fps variant. Those videos also play with fractional frame rates in the youtube addon. Log is present.
At one point I put a DVD in my optical drive while a video was playing or on pause in MyTube. This did not cause any issues, but wrote excessive errors from inputstream.adaptive into the log.

How can I send you the logs without them being open to the public?

**Comment by lekma** [comment] 2024-10-27 15:26
sorry, was busy,

for the logs i really prefer if you put them on pastebin or something else.

for the audio problem: i started experiencing what you describe and solved(?) it by switching to alsa using ```KODI_AE_SINK=ALSA kodi``` to start kodi (you have to setup your audio in kodi after that). since then it didn't happen again...

to be honest you seem to be experiencing a perfect storm of hardware/inputstream issues, do you have another comp to test and remove some variables

**Comment by OnkelArmus** [comment] 2024-10-27 16:15
I will test it with alsa and on my main PC.
About fractional frame rates: It does not work for almost-60fps videos ether. Does it only work for 24fps? Same behaviour in Kodi's youtube addon. Do you need the logs about it?
Here are my logs:
https://pastebin.com/QfmB7rvd
https://pastebin.com/KkkZ7zKp
https://pastebin.com/HuBswVEy
https://pastebin.com/iUVfkgQU

**Comment by lekma** [comment] 2024-10-27 16:49
no it's the same for 24fps or 60. please just to be sure set all settings of 'service.yt-dlp' to defaults and adjust only the framerate settings in 'mytube' settings (maybe the override logic is bugged)

**Comment by OnkelArmus** [comment] 2024-10-31 11:01
Did you fix the missing audio problem? I've noticed updates to your dependencies and I'm unable to reproduce the error.
Integer frame rates don't work for the 30 and 60 fps variants. Works for 24 fps. I'm not sure about the other variants. I've loaded defaults on all settings pages in MyTube beforehand. The services are untouched.

**Comment by OnkelArmus** [comment] 2026-02-03 18:21
Hi there! I hope you're doing well.
I know Youtube messed things up again and I've noticed that you're updating yt-dlp in the last few days but I'm unsure if it's about the issue I'm experiencing, which is no audio. No decoders are blocked in settings, input stream adaptive is set to manual OSD. One audio stream is shown, but I don't get audio playback.

**Comment by lekma** [comment] 2026-02-04 06:27
> Hi there! I hope you're doing well.

I'm doing ok, very busy irl, so... (thanks for asking)

> I know Youtube messed things up again and I've noticed that you're updating yt-dlp in the last few days but I'm unsure if it's about the issue I'm experiencing, which is no audio. No decoders are blocked in settings, input stream adaptive is set to manual OSD. One audio stream is shown, but I don't get audio playback.

Yeah, YT went back to work on annoying everybody, please update all addons, reset all settings to default (including service.yt-dlp) and try again. I'll need a videoid and probably a kodi log.

**Comment by lekma** [comment] 2026-02-04 07:40
also did you check the video streams (it reminds me of #8)...

**Comment by OnkelArmus** [comment] 2026-02-04 09:07
You're right with #8. I will continue there, so it's in the right context.
